name = "hdfs"

[namespace.storage]

[namespace.storage.new]
required = ["endpoint"]
optional = ["storage_features", "default_storage_pairs", "work_dir"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.content-length]
type = "int64"
description = "length in bytes for regular files; system-dependent for others"

[infos.object.meta.ObjectMode]
type = "uint32"
description = "file mode bits"

[infos.object.meta.LastModified]
type = "time.Time"
description = "modification time"