name = "hdfs"

[namespace.storage]

[namespace.storage.new]
required = ["endpoint"]
optional = ["storage_features", "default_storage_pairs", "work_dir"]

[namespace.storage.op.create]
optional = ["object_mode"]

[namespace.storage.op.delete]
optional = ["object_mode"]

[namespace.storage.op.list]
optional = ["list_mode"]

[namespace.storage.op.read]
optional = ["offset", "io_callback", "size"]

[namespace.storage.op.stat]
optional = ["object_mode"]

[namespace.storage.op.write]
optional = ["content_md5", "content_type", "io_callback"]

[pairs.storage_features]
type = "StorageFeatures"
description = "set storage features"

[pairs.default_storage_pairs]
type = "DefaultStoragePairs"
description = "set default pairs for storager actions"

[infos.object.meta.name]
type = "string"
description = "base name of the file"

[infos.object.meta.size]
type = "int64"
description = "length in bytes for regular files; system-dependent for others"

[infos.object.meta.mode]
type = "uint32"
description = "file mode bits"

[infos.object.meta.ModTime]
type = "time.Time"
description = "modification time"

[infos.object.meta.IsDir]
type = "bool"
description = "abbreviation for Mode().IsDir()"

[infos.object.meta.Sys]
type = "interface{}"
description = "underlying data source (can return nil)"