name: "Integration Test"

on: [push, pull_request]

jobs:
  integration_test:
    name: "Integration Test"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ "1.15", "1.16" ]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        env:
          STORAGE_HDFS_INTEGRATION_TEST: "on"
          STORAGE_HDFS_ENDPOINT: "tcp:127.0.0.1:9000"
        run: make integration_test